# Generated by Django 5.2.6 on 2025-10-01 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('enroll_no', models.AutoField(primary_key=True, serialize=False)),
                ('course', models.CharField(max_length=100)),
                ('college', models.CharField(max_length=100)),
                ('duration_from', models.DateField()),
                ('duration_to', models.DateField()),
                ('grade', models.CharField(max_length=10)),
            ],
        ),
    ]
