# Generated by Django 5.2.6 on 2025-10-01 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificate_app', '0003_technology'),
    ]

    operations = [
        migrations.AlterField(
            model_name='numbertracker',
            name='last_enroll_no',
            field=models.CharField(default='PMS|2025|ST|139|1001', max_length=100),
        ),
        migrations.AlterField(
            model_name='numbertracker',
            name='last_verification_no',
            field=models.CharField(default='CDPMSINT1001', max_length=100),
        ),
    ]
