# Generated by Django 5.2.6 on 2025-10-01 09:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificate_app', '0004_alter_numbertracker_last_enroll_no_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('enroll_no', models.IntegerField(unique=True)),
                ('verification_no', models.IntegerField(unique=True)),
                ('college', models.CharField(max_length=100)),
                ('start_duration_from', models.DateField()),
                ('end_duration_to', models.DateField()),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='certificate_app.course')),
                ('grade', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='certificate_app.grade')),
                ('training_course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='certificate_app.technology')),
                ('training_duration', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='certificate_app.training')),
            ],
        ),
    ]
