# Generated by Django 5.2.6 on 2025-10-01 09:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificate_app', '0005_student_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_data',
            name='training_technology',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='certificate_app.technology'),
        ),
        migrations.AlterField(
            model_name='student_data',
            name='training_course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='certificate_app.training'),
        ),
    ]
