# Generated by Django 5.2.6 on 2025-10-01 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificate_app', '0006_student_data_training_technology_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_data',
            name='enroll_no',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='student_data',
            name='verification_no',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
