# Generated by Django 5.2.6 on 2025-10-01 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificate_app', '0007_alter_student_data_enroll_no_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NumberTracker_award',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_sr_no', models.CharField(default='PMS|2025|ST|139|AWD01', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Student_award_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('sr_no', models.CharField(max_length=50, unique=True)),
                ('award', models.CharField(max_length=100)),
                ('college', models.CharField(max_length=100)),
                ('issued_date', models.DateField()),
            ],
        ),
    ]
